const Discord = require('discord.js')
const channel = require('../schemes/channel')

module.exports.run = async (client, interaction, translations) => {
const { version } = require("discord.js")
        var serversembed = new Discord.MessageEmbed()
        .setTitle(`📝 ${translations["022"].replace("{{username}}", client.user.username)}`)
        .addField(`🤖 | Bot certifié :`,`:x:`)
        .addField(`:satellite: | ${translations["024"]}`,`${client.guilds.cache.size}`, true)
        .addField(`:ping_pong: | ${translations["025"]}: `, Math.round(client.ws.ping) + "ms", true)
        .addField(`📋 ${translations["026"]} :`, `${client.user.username}`, true)
        .addField(`🔗 ${translations["028"]} :`, "#" + `${client.user.discriminator}`, true)
        .addField(`📊 ${translations["027"]} :`, `${client.guilds.cache.reduce((acc, guild) => acc + guild.memberCount, 0)}`, true)
        .addField(`🔧 ${translations["029"]}:`, `v${version}`, true)
        .addField(`🔨 ${translations["030"]} :`, `${process.version}`, true)
        .addField(translations["031"], (Math.round(client.uptime / (1000 * 60 * 60))) + ' heures ' + (Math.round(client.uptime / (1000 * 60)) % 60) + ' minutes ' + (Math.round(client.uptime / 1000) % 60) + ' secondes ', true)
        .addField(`💾 ${translations["032"]}`, `${(process.memoryUsage().heapUsed / 1024 / 1024).toFixed(2)}` + " MB", true)
        .addField(translations["033"], "**Artlfmj#0001**", true)
        .setFooter(`${client.user.tag}`, client.user.displayAvatarURL())

        .setColor("RANDOM")
        .setThumbnail(client.user.avatarURL)
        .setTimestamp()
        interaction.reply({embeds : [serversembed]})
}
